# Coding Assignment: Implementation of ANN
### Name:    Deepesh Yadav
### Roll no:  171380
### Batch:    CS-66

In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix,accuracy_score

In [92]:
#importing dataset
df = pd.read_csv('sonar-all-data.csv')
df.head()

0.02  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167   0.018  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

    0.009  0.0032  0  
0  0.0052  0.0044  0  
1  0.0095  0.0078  0  
2  0.0040  0.0117  0  
3  0.0107  0.0094  0  
4  0.0051  0.0062  0  

[5 rows x 61 columns]

In [93]:
#spliting data into features and labels
X = df.iloc[:,0:60]  #features
Y = df.iloc[:,60:61]  #labels

In [94]:
#splitting dataset into training and testing data

x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 3)  


In [95]:
clf = Sequential()
clf.add(Dense(input_dim=60,units=31,kernel_initializer= 'uniform', activation ='relu'))

In [96]:
clf.add(Dense(units=31,activation ='relu',kernel_initializer ='uniform'))

In [97]:
clf.add(Dense(units =1,kernel_initializer='uniform',activation='relu'))

In [98]:
clf.compile(optimizer ='adam',loss='binary_crossentropy',metrics = ['accuracy'])

In [99]:
clf.fit(x_train,y_train,batch_size=10,epochs = 100)

Epoch 1/100
165/165 [==============================] - 0s 577us/step - loss: 2.1435 - accuracy: 0.4667
Epoch 2/100
165/165 [==============================] - 0s 85us/step - loss: 1.3092 - accuracy: 0.4667
Epoch 3/100
165/165 [==============================] - 0s 89us/step - loss: 0.9134 - accuracy: 0.4667
Epoch 4/100
165/165 [==============================] - 0s 92us/step - loss: 0.7202 - accuracy: 0.4848
Epoch 5/100
165/165 [==============================] - 0s 88us/step - loss: 0.6734 - accuracy: 0.5758
Epoch 6/100
165/165 [==============================] - 0s 87us/step - loss: 0.6662 - accuracy: 0.6242
Epoch 7/100
165/165 [==============================] - 0s 77us/step - loss: 0.6591 - accuracy: 0.6000
Epoch 8/100
165/165 [==============================] - 0s 87us/step - loss: 0.6543 - accuracy: 0.6242
Epoch 9/100
165/165 [==============================] - 0s 87us/step - loss: 0.6511 - accuracy: 0.6424
Epoch 10/100
165/165 [==============================] - 0s 86us/step - loss: 0.63

165/165 [==============================] - 0s 75us/step - loss: 0.2948 - accuracy: 0.8000
Epoch 81/100
165/165 [==============================] - 0s 78us/step - loss: 0.3089 - accuracy: 0.7818
Epoch 82/100
165/165 [==============================] - 0s 82us/step - loss: 0.2820 - accuracy: 0.8121
Epoch 83/100
165/165 [==============================] - 0s 75us/step - loss: 0.2705 - accuracy: 0.8424
Epoch 84/100
165/165 [==============================] - 0s 73us/step - loss: 0.2702 - accuracy: 0.7879
Epoch 85/100
165/165 [==============================] - 0s 72us/step - loss: 0.2667 - accuracy: 0.8061
Epoch 86/100
165/165 [==============================] - 0s 78us/step - loss: 0.2895 - accuracy: 0.7939
Epoch 87/100
165/165 [==============================] - 0s 70us/step - loss: 0.2633 - accuracy: 0.8121
Epoch 88/100
165/165 [==============================] - 0s 75us/step - loss: 0.2586 - accuracy: 0.8121
Epoch 89/100
165/165 [==============================] - 0s 76us/step - loss: 0.2625 - 

In [100]:
pred = clf.predict(x_test)

In [101]:
cm = confusion_matrix(y_test,pred.round())
print(cm)

[[13  6  0]
 [ 3 18  2]
 [ 0  0  0]]


In [102]:
print('Accuracy using an ANN :',accuracy_score(y_test, pred.round()))

Accuracy using an ANN : 0.7380952380952381
